// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGIN5Q_mMgvgtGBpiiJoW1KJogM8gmBk4',
    appId: '1:453112287485:web:1d4c946624a6e1bc826e94',
    messagingSenderId: '453112287485',
    projectId: 'watershop-26789',
    authDomain: 'watershop-26789.firebaseapp.com',
    storageBucket: 'watershop-26789.appspot.com',
    measurementId: 'G-F568YW6TF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXfoQ_KpbxQX6fs9xP74vraVUGXvDDl0k',
    appId: '1:453112287485:android:acdd62b880960e87826e94',
    messagingSenderId: '453112287485',
    projectId: 'watershop-26789',
    storageBucket: 'watershop-26789.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIlZNTMe4SAyOVWEExsI_7xlACeDL1Y5E',
    appId: '1:453112287485:ios:ed8c8e60fce4ab77826e94',
    messagingSenderId: '453112287485',
    projectId: 'watershop-26789',
    storageBucket: 'watershop-26789.appspot.com',
    iosClientId: '453112287485-lsm8smctieo2gqen6m45nqvenjvprgdk.apps.googleusercontent.com',
    iosBundleId: 'com.flutterthailand.applicationDrinkingWaterShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIlZNTMe4SAyOVWEExsI_7xlACeDL1Y5E',
    appId: '1:453112287485:ios:aa36f9aa076ab118826e94',
    messagingSenderId: '453112287485',
    projectId: 'watershop-26789',
    storageBucket: 'watershop-26789.appspot.com',
    iosClientId: '453112287485-ilgormqfofstakuhih5hji96i68i4rr2.apps.googleusercontent.com',
    iosBundleId: 'com.flutterthailand.applicationDrinkingWaterShop.RunnerTests',
  );
}
